//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOOBOSEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int pkid { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<int> ProductLocationID { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string Description { get; set; }
        public Nullable<double> UnitPrice { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductLocation ProductLocation { get; set; }
    }
}
