//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOOBOSEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLocationLog
    {
        public int pkid { get; set; }
        public Nullable<int> ProductLocationID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Location { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> AvgValue { get; set; }
        public string ChangeType { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
