//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOOBOSEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UOM()
        {
            this.Products = new HashSet<Product>();
            this.ProductCategories = new HashSet<ProductCategory>();
            this.UOM1 = new HashSet<UOM>();
        }
    
        public int pkid { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> BaseID { get; set; }
        public Nullable<double> ConversionFactor { get; set; }
        public string Abbrev { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UOM> UOM1 { get; set; }
        public virtual UOM UOM2 { get; set; }
    }
}
