//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOOBOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public System.DateTime DateKey { get; set; }
        public Nullable<int> DateInt { get; set; }
        public Nullable<int> YearKey { get; set; }
        public Nullable<int> HalfYearKey { get; set; }
        public Nullable<int> QuarterKey { get; set; }
        public Nullable<int> MonthKey { get; set; }
        public Nullable<int> MonthOfYear { get; set; }
        public Nullable<int> MonthOfHalfYear { get; set; }
        public Nullable<int> MonthOfQuarter { get; set; }
        public Nullable<int> QuarterOfYear { get; set; }
        public Nullable<int> QuarterOfHalfYear { get; set; }
        public Nullable<int> HalfYearOfYear { get; set; }
        public Nullable<int> DayOfYear { get; set; }
        public Nullable<int> DayOfHalfYear { get; set; }
        public Nullable<int> DayOfQuarter { get; set; }
        public Nullable<int> DayOfMonth { get; set; }
        public Nullable<int> DayOfWeekMon { get; set; }
        public Nullable<int> DayOfWeekSun { get; set; }
        public Nullable<int> WeekOfYearISO { get; set; }
    }
}
