//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOOBOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLog
    {
        public int pkid { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public Nullable<int> OrderlineID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<int> LineNum { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string ChangeType { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
