//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOOBOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleLine
    {
        public int pkid { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<int> ProductLocationID { get; set; }
        public string Description { get; set; }
        public Nullable<int> LineNum { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> UnitPrice { get; set; }
    
        public virtual ProductLocation ProductLocation { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
